enabled_fonts:
  - 'https://www.google.com/webfonts/family?family=Saira Condensed&subset=latin#regular'
  - 'https://www.google.com/webfonts/family?family=Saira&subset=latin#700'
load_all_enabled_fonts: 1
dependencies:
  module:
    - fontyourface
_core:
  default_config_hash: VFARUiyAb_ZpoNS4f3rHcN6oMZyIjMyr2cfbY99tiMo
