<?php

/**
 * @file
 * Integration install / update hooks.
 */

/**
 * V1.0.19 - IS form fixes.
 */
function presence_integrations_update_8011() {

  // Import feature code.
  $feature_list = [
    'presence_integrations',
  ];
  // See: Drupal [#3017765].
  $assigner = \Drupal::service('features_assigner');
  $assigner->assignConfigPackages();

  \Drupal::service('features.manager')->import($feature_list);
}
