<?php

/**
 * @file
 * Functions to support adminimal admin toolbar.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function presence_admin_toolbar_preprocess_html(&$variables) {
  // Add presence-admin-toolbar class to the body.
  if (_presence_admin_toolbar_is_access()) {
    $variables['attributes']['class'][] = 'presence-admin-toolbar';
  }
}

/**
 * Implements hook_page_attachments_alter().
 */
function presence_admin_toolbar_page_attachments_alter(array &$page) {
  // Attaches css assets globally.
  if (_presence_admin_toolbar_is_access()) {
    $page['#attached']['library'][] = 'presence_admin_toolbar/presence-admin-toolbar';

    // Add Open Sans css file.
    if (!(\Drupal::config('presence_admin_toolbar.settings')->get('avoid_custom_font'))) {
      $page['#attached']['library'][] = 'presence_admin_toolbar/google-fonts';
    }
  }
}

/**
 * Implements hook_toolbar_alter().
 */
function presence_admin_toolbar_toolbar_alter(&$items) {
  // Add class to the user tab so it can be moved to the right.
  if (_presence_admin_toolbar_is_access()) {
    $items['user']['#wrapper_attributes']['class'] = ['user-toolbar-tab'];
  }
}

/**
 * Helper function for checking user permission.
 *
 * We reallly only want to add styling and changes to toolbar when the user has
 * access.
 *
 * Returns TRUE or FALSE.
 */
function _presence_admin_toolbar_is_access() {
  $user = \Drupal::currentUser();
  return $user->hasPermission('access toolbar');
}
