enabled_fonts:
  - 'https://www.google.com/webfonts/family?family=Poppins&subset=latin#700'
  - 'https://www.google.com/webfonts/family?family=PT Serif&subset=latin#regular'
load_all_enabled_fonts: 1
dependencies:
  module:
    - fontyourface
